[package]
name = "http_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.17"
url = "2.2.2"
mio = "0.6.11"
regex = "1"
nix = "0.20.0"
rustyline = "10.0"